version: '3.8'

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile-debug
    #command: /dlv --listen=:47979 --headless=true --api-version=2 --accept-multiclient --check-go-version=false --only-same-user=false exec /app/server/producer/cmd/producer
    entrypoint: /dlv --listen=:47979 --headless=true --api-version=2 --accept-multiclient --check-go-version=false --only-same-user=false exec /app/server/producer/cmd/producer
    container_name: producer
    ports:
      - "7979:7979"
      - "47979:47979"
      - "44001:4001"
    security_opt:
      - "apparmor:unconfined"
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - server-data:/app/server/producer
    networks:
      - pet-backend-producer
      - pet-backend-shared

volumes:
  server-data:
    name: pet-server-vol

networks:
  pet-backend-producer:
    external: true
  pet-backend-shared:
    external: true