version: '3.9'

services:
  advertd:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/server/advertd/cmd/advertd
    container_name: advertd
    ports:
      - "7000:7000" #advertd
      - "7200:7200" #pprof
    security_opt:
      - "apparmor:unconfined"
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 1G
        reservations:
          cpus: 1
          memory: 256M
    volumes:
      - persistent-data:/pet
    networks:
      - pet-backend-advertd
      - pet-backend-shared

volumes:
  persistent-data:
    external: true
    name: pet-persistent-vol

networks:
  pet-backend-advertd:
    external: true
  pet-backend-shared:
    external: true

# E:\tools\nfs\WinNFSd.exe e:\tools\nfs\share\pet /pet
# docker volume create --driver local --opt type=nfs --opt o=nfsvers=3,addr=host.docker.internal,rw --opt device=:/pet pet-persistent-vol