version: '3.8'

services:
  advertd:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/server/advertd/cmd/advertd
    container_name: advertd
    ports:
      - "7979:7979"
      - "44001:4001"
    security_opt:
      - "apparmor:unconfined"
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - server-data:/app/server/advertd
    networks:
      - pet-backend-advertd
      - pet-backend-shared

volumes:
  server-data:
    name: pet-server-vol

networks:
  pet-backend-advertd:
    external: true
  pet-backend-shared:
    external: true