version: '3.8'

services:
  advertd:
    build:
      context: .
      dockerfile: Dockerfile-debug
    entrypoint: /dlv --listen=:7100 --headless=true --api-version=2 --accept-multiclient --check-go-version=false --only-same-user=false exec /app/server/advertd/cmd/advertd
    container_name: advertd
    ports:
      - "7000:7000" #advertd
      - "7100:7100" #delve
      - "7200:7200" #pprof
    security_opt:
      - "apparmor:unconfined"
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - persistent-data:/pet
    networks:
      - pet-backend-advertd
      - pet-backend-shared

volumes:
  persistent-data:
    external: true
    name: pet-persistent-vol

networks:
  pet-backend-advertd:
    external: true
  pet-backend-shared:
    external: true