version: '3.8'

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile-debug
    command: /dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient --check-go-version=false --only-same-user=false exec /app/server/producer/cmd/producer
    container_name: producer
    ports:
      - "8989:8989"
      - "40000:40000"
    security_opt:
      - "apparmor:unconfined"
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - server-data:/app/server

volumes:
  server-data:
    name: pet-server-vol

networks:
  backend:
    name: pet-net
    driver: custom-driver




    #Allow Delve to compile your application:
    #dlv debug --headless --listen=:40000 --api-version=2 --accept-multiclient
    #Or compile the application using Go 1.11 or newer:
    #go build -gcflags "all=-N -l" github.com/app/demo
    #and then run it with Delve using the following command:
    #dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient exec ./demo.exe