version: '3.8'

services:
  redis:
    restart: always
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ../../persistent/redis/advert/data:/data
    networks:
      - pet-backend-advertd

networks:
  pet-backend-advertd:
    external: true